#!/bin/sh

if [ "x$PERFHOME" == "x" ]
then
    $PERFHOME=.
fi

JFLAGS=""
if [ -e ./getflags.sh ]
then
    $JFLAGS="`./getflags.sh`"
fi

$PERFHOME/perf42 record -F 99 java -agentpath:$PERFHOME/libnativejava.so -XX:+PreserveFramePointer $@

